### ISSUE TITLE
Need to fix latte command error (some commands are using -dump flag without -i flag)

### ISSUE THREAD

**Issue by vidyas00** [microsoft/NetPerfTest#16]
The below commands are failing with error "-dump can be specified only for iteration (-i) based tests" 

latte.exe -sa -c -a 172.16.1.4:50000 -t 10 -hist -hc 98 -hl 10 -tcp -snd b  -so -dump C:\temp\msdbg.VM1.perftest\latte\tcp.t10.b.data.txt > C:\temp\msdbg.VM1.perftest\latte\tcp.t10.b.txt

latte.exe -sa -c -a 172.16.1.4:50000 -t 10 -hist -hc 98 -hl 10 -tcp -snd b -group 0 -rio -riopoll 100000000000 -so -dump C:\temp\msdbg.VM1.perftest\latte\tcp.t10.b.OPT.data.txt > C:\temp\msdbg.VM1.perftest\latte\tcp.t10.b.OPT.txt

latte.exe -sa -c -a 172.16.1.4:50000 -t 10 -hist -hc 98 -hl 10 -udp -snd b  -so -dump C:\temp\msdbg.VM1.perftest\latte\udp.t10.b.data.txt > C:\temp\msdbg.VM1.perftest\latte\udp.t10.b.txt

latte.exe -sa -c -a 172.16.1.4:50000 -t 10 -hist -hc 98 -hl 10 -udp -snd b -group 0 -rio -riopoll 100000000000 -so -dump C:\temp\msdbg.VM1.perftest\latte\udp.t10.b.OPT.data.txt > C:\temp\msdbg.VM1.perftest\latte\udp.t10.b.OPT.txt

**Comment by vidyas00** [comment]
These are now fixed and verified

**Comment by pranalij** [comment]
I am trying to measure the latency through multiple interfaces from the same host. I noticed latte has a -bl command. An help/example on how I can use it ?

**Comment by vidyas00** [comment]
Here's an example:

Server: latte.exe -a <server-IP>:<server-port> <any additional params such as -rio -i -riopoll etc> -<protocol>
Client: latte.exe -so -c -a <server-ip>:<server-port> <any additional params such as -rio -i -riopoll -hist -hl -hc etc> -<protocol> -bl <client-IP>

**Comment by vidyas00** [comment]
Here's an example:

Server: latte.exe -a <server-IP>:<server-port> <any additional params> -<protocol>
Client: latte.exe -so -c -a <server-ip>:<server-port> <additional params> -<protocol> -bl <client-IP>

**Comment by vidyas00** [comment]
Not sure why some text in my comments are getting truncated. however @pranalij to answer your question, on the client side command, just -bl client_IP should be sufficient to let latte know which NIC is to be used for the test
