### ISSUE TITLE
Is there any way to add multiple ports? 

### ISSUE THREAD

**Issue by vagnerpilar** [microsoft/NetPerfTest#17]
Trying to add multiple ports (dual port, bidirectional test) is there any way? noticed that we cannot 
 add multiple  -DestIP and  -Srclp .\PERFTEST.PS1 -DestIp 192.168.1.2 -SrcIp 192.168.1.3 -OutDir "C:\temp\"

**Comment by omarcardona** [comment]
Hi,
LATTE.exe proper does not support multi-destination.  The script herein is primarily an automation wrapper for simplified execution.

For multi-destination, you would need to use a separate tool.  Alternately you can consider multiple processes executing LATTE.exe concurrently.

**Comment by vagnerpilar** [comment]
Not really, the ideia is not even use LATTE.exe, the main point here is try to use NTttcp single port unidirectional, bidirectional and also dual port uni and bidi. This tool is strong and capable of that. Just need to add the parameters for other DestIPs, etc. LATTE actually is not a requirement in this comment.
